name = "JuGrad"
uuid = "ee9dcbef-c695-46c6-b3c8-5efbf2084a3e"
authors = ["Yıldırım Akbal"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
